// <auto-generated />
using System;
using DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(DUAN1_QL_BANQUANAOContext))]
    [Migration("20240618140238_inital")]
    partial class inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DAL.Models.Chatlieu", b =>
                {
                    b.Property<string>("MaChatLieu")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaChatLieu")
                        .HasName("PK__CHATLIEU__453995BC216B4E29");

                    b.ToTable("CHATLIEU", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Hoadon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaHoaDon")
                        .HasName("PK__HOADON__835ED13B4B65AD27");

                    b.HasIndex("MaKhuyenMai");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("SoDienThoai");

                    b.ToTable("HOADON", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Hoadonchitiet", b =>
                {
                    b.Property<string>("MaHoaDonChiTiet")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaHoaDonChiTiet")
                        .HasName("PK__HOADONCH__6C2FD0CE8DA2E8DC");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaSanPham");

                    b.ToTable("HOADONCHITIET", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Khachhang", b =>
                {
                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime");

                    b.HasKey("SoDienThoai")
                        .HasName("PK__KHACHHAN__0389B7BC9834F37F");

                    b.ToTable("KHACHHANG", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Khuyenmai", b =>
                {
                    b.Property<string>("MaKhuyenMai")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KieuKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MucGiam")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaKhuyenMai")
                        .HasName("PK__KHUYENMA__6F56B3BD44B9118C");

                    b.ToTable("KHUYENMAI", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Kichthuoc", b =>
                {
                    b.Property<string>("MaKichThuoc")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaKichThuoc")
                        .HasName("PK__KICHTHUO__22BFD664F4B2D17F");

                    b.ToTable("KICHTHUOC", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Mausac", b =>
                {
                    b.Property<string>("MaMauSac")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaMauSac")
                        .HasName("PK__MAUSAC__B9A9116213278034");

                    b.ToTable("MAUSAC", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Nhanvien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("NamSinh")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("datetime");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("MaNhanVien")
                        .HasName("PK__NHANVIEN__77B2CA47A9DB6165");

                    b.HasIndex(new[] { "MaTaiKhoan" }, "UQ__NHANVIEN__AD7C652875B490BD")
                        .IsUnique();

                    b.ToTable("NHANVIEN", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Salesanpham", b =>
                {
                    b.Property<string>("MaSale")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.HasKey("MaSale")
                        .HasName("PK__SALESANP__B234B7A7CFE930E9");

                    b.ToTable("SALESANPHAM", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Sanpham", b =>
                {
                    b.Property<string>("MaSanPham")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<double>("GiaBan")
                        .HasColumnType("float");

                    b.Property<string>("MaThuongHieu")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaSanPham")
                        .HasName("PK__SANPHAM__FAC7442DE9142573");

                    b.HasIndex("MaThuongHieu");

                    b.ToTable("SANPHAM", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Sanphamchitiet", b =>
                {
                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<string>("MaChatLieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaKichThuoc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaMauSac")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaSale")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaSanPhamChiTiet")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaThuongHieu")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("MoTaChiTiet")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasIndex("MaChatLieu");

                    b.HasIndex("MaKichThuoc");

                    b.HasIndex("MaMauSac");

                    b.HasIndex("MaSale");

                    b.HasIndex("MaSanPham");

                    b.HasIndex("MaThuongHieu");

                    b.ToTable("SANPHAMCHITIET", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Taikhoan", b =>
                {
                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("MaTaiKhoan")
                        .HasName("PK__TAIKHOAN__AD7C65296F5F9EA2");

                    b.ToTable("TAIKHOAN", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Thuonghieu", b =>
                {
                    b.Property<string>("MaThuongHieu")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaThuongHieu")
                        .HasName("PK__THUONGHI__A3733E2CE42662E1");

                    b.ToTable("THUONGHIEU", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Hoadon", b =>
                {
                    b.HasOne("DAL.Models.Khuyenmai", "MaKhuyenMaiNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("MaKhuyenMai")
                        .IsRequired()
                        .HasConstraintName("FK__HOADON__MaKhuyen__0D7A0286");

                    b.HasOne("DAL.Models.Nhanvien", "MaNhanVienNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("MaNhanVien")
                        .IsRequired()
                        .HasConstraintName("FK__HOADON__MaNhanVi__0C85DE4D");

                    b.HasOne("DAL.Models.Khachhang", "SoDienThoaiNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("SoDienThoai")
                        .IsRequired()
                        .HasConstraintName("FK__HOADON__SoDienTh__0E6E26BF");

                    b.Navigation("MaKhuyenMaiNavigation");

                    b.Navigation("MaNhanVienNavigation");

                    b.Navigation("SoDienThoaiNavigation");
                });

            modelBuilder.Entity("DAL.Models.Hoadonchitiet", b =>
                {
                    b.HasOne("DAL.Models.Hoadon", "MaHoaDonNavigation")
                        .WithMany("Hoadonchitiets")
                        .HasForeignKey("MaHoaDon")
                        .IsRequired()
                        .HasConstraintName("FK__HOADONCHI__MaHoa__114A936A");

                    b.HasOne("DAL.Models.Sanpham", "MaSanPhamNavigation")
                        .WithMany("Hoadonchitiets")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__HOADONCHI__MaSan__123EB7A3");

                    b.Navigation("MaHoaDonNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("DAL.Models.Nhanvien", b =>
                {
                    b.HasOne("DAL.Models.Taikhoan", "MaTaiKhoanNavigation")
                        .WithOne("Nhanvien")
                        .HasForeignKey("DAL.Models.Nhanvien", "MaTaiKhoan")
                        .IsRequired()
                        .HasConstraintName("FK__NHANVIEN__MaTaiK__07C12930");

                    b.Navigation("MaTaiKhoanNavigation");
                });

            modelBuilder.Entity("DAL.Models.Sanpham", b =>
                {
                    b.HasOne("DAL.Models.Thuonghieu", "MaThuongHieuNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("MaThuongHieu")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAM__MaThuon__71D1E811");

                    b.Navigation("MaThuongHieuNavigation");
                });

            modelBuilder.Entity("DAL.Models.Sanphamchitiet", b =>
                {
                    b.HasOne("DAL.Models.Chatlieu", "MaChatLieuNavigation")
                        .WithMany()
                        .HasForeignKey("MaChatLieu")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCH__MaCha__7D439ABD");

                    b.HasOne("DAL.Models.Kichthuoc", "MaKichThuocNavigation")
                        .WithMany()
                        .HasForeignKey("MaKichThuoc")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCH__MaKic__7C4F7684");

                    b.HasOne("DAL.Models.Mausac", "MaMauSacNavigation")
                        .WithMany()
                        .HasForeignKey("MaMauSac")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCH__MaMau__7E37BEF6");

                    b.HasOne("DAL.Models.Sanpham", "MaSaleNavigation")
                        .WithMany()
                        .HasForeignKey("MaSale")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCH__MaSal__00200768");

                    b.HasOne("DAL.Models.Sanpham", "MaSanPhamNavigation")
                        .WithMany()
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCH__MaSan__7B5B524B");

                    b.HasOne("DAL.Models.Thuonghieu", "MaThuongHieuNavigation")
                        .WithMany()
                        .HasForeignKey("MaThuongHieu")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCH__MaThu__7F2BE32F");

                    b.Navigation("MaChatLieuNavigation");

                    b.Navigation("MaKichThuocNavigation");

                    b.Navigation("MaMauSacNavigation");

                    b.Navigation("MaSaleNavigation");

                    b.Navigation("MaSanPhamNavigation");

                    b.Navigation("MaThuongHieuNavigation");
                });

            modelBuilder.Entity("DAL.Models.Hoadon", b =>
                {
                    b.Navigation("Hoadonchitiets");
                });

            modelBuilder.Entity("DAL.Models.Khachhang", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("DAL.Models.Khuyenmai", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("DAL.Models.Nhanvien", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("DAL.Models.Sanpham", b =>
                {
                    b.Navigation("Hoadonchitiets");
                });

            modelBuilder.Entity("DAL.Models.Taikhoan", b =>
                {
                    b.Navigation("Nhanvien");
                });

            modelBuilder.Entity("DAL.Models.Thuonghieu", b =>
                {
                    b.Navigation("Sanphams");
                });
#pragma warning restore 612, 618
        }
    }
}
